### ISSUE TITLE
Exp on image_datasets?

### ISSUE THREAD

**Issue by brave-cattle** [ykwon0407/fast_dist_shapley#1]
Hi!
It seems that the experiments on cifar10, fashion and mnist cannot work.
I cannot download the "{dataset}_tr_ext_pretrained_resnet.pkl" in line 136 of data.py. And "prep_non_reg_data.py" doesn't provide any clues.

**Comment by ykwon0407** [comment]
Hi @brave-cattle, I am not actively maintaining this repository and I am using this repository just to provide key parts of the proposed algorithm. If you are still interested in the files, please send me an email!
